---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
  spec:
    containers:
      - name: myspringbootapp
        image: hr143heart/mydemoapp:latest
        ports:
          - containerPort: 9099
            protocol: TCP
         
